### ISSUE TITLE
Support Redmine 4.2 installation with handling blankslate gem

### ISSUE THREAD

**Issue by sanak** [hidakatsuya/action-setup-redmine#6]
Related with the following `blankslate` gem issue for Redmine 4.2,
* [CI redmine:4.2-stable "LoadError: cannot load such file -- blankslate" error · Issue #33 · gtt-project/redmine_custom_fields_groups](https://github.com/gtt-project/redmine_custom_fields_groups/issues/33)

I tried to setup custom `Gemfile.local` after this action's setup and a plugin's checkout,
* [Fix 'LoadError: cannot load such file -- blankslate' in CI redmine:4.2 by sanak · Pull Request #34 · gtt-project/redmine_custom_fields_groups](https://github.com/gtt-project/redmine_custom_fields_groups/pull/34)

but I encountered the following error from the last step in this action.
* CI error: https://github.com/gtt-project/redmine_custom_fields_groups/actions/runs/9676803332/job/26697164075?pr=34#step:2:750
* Last step in this action: https://github.com/hidakatsuya/action-setup-redmine/blob/main/action.yml#L146-L150

I am thinking to create PR for `blankslate` gem handling code inside this action, but is this the right direction ?

Other possibility is deleting the last `Set up database` step from this action and handling the step in this action's client (=plugin) side, but I think that it requires another client side modification.

**Comment by sanak** [comment]
Sorry, the error cause was not the last step, but ruby setup part from local investigation (https://github.com/sanak/action-setup-redmine/pull/1). 🙇💦
So, removing the last step is no meaning.
I will create PR to support Redmine 4.2.

**Comment by hidakatsuya** [comment]
Sorry for the late reply. Furthermore, thank you for your report, investigation, and suggestions. I'll check your pull request.

**Comment by sanak** [comment]
Okay, no problem.
Thanks a lot! 🙇
